import React from "react";
import "@/styles/globals.css";
import Navbar from "./Navbar";
import NextUIProvider from "./NextUIProvider";
import Providers from "./Providers";
import { Toaster } from "@/components/ui/sonner";
import CenteredFooterWithSocialLinks from "@/nextui/CenteredFooterWithSocialLinks";
import { Montserrat } from "next/font/google";
import { cn } from "@/lib/cn";
import { Spotlight } from "@/components/ui/Spotlight";
import prisma from "@/prisma/client";

export const metadata = {
	title: "The English School Student Elections",
	description: "Generated by create next app",
};

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
});

export default async function RootLayout({ children }) {
	const faqs = await prisma.faq.count();
	return (
		<html lang="en" className={cn(montserrat.className, "dark")}>
			<Providers>
				<body>
					<NextUIProvider>
						<Navbar faqsCount={faqs} />
						<main className="flex min-h-screen shadow-md bg-black flex-col items-center justify-between">
							<div className="bg-dot-white/25 min-h-screen w-full rounded-b-[20px]">
								<Spotlight className="-top-40 left-0 md:left-60 md:-top-20" fill="white" />
								{children}
							</div>
						</main>
						<Toaster />
						<CenteredFooterWithSocialLinks />
					</NextUIProvider>
				</body>
			</Providers>
		</html>
	);
}
